version: "3.9"

services:
  app:
    build: .
    container_name: yandex_audio_app
    command: >
      bash -c "
      alembic upgrade head &&
      python seeder.py &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    environment:
      DB_HOST: db
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: